[tool.poetry]
name = "exercism"
version = "0.1.0"
description = ""
authors = ["Chaitanya Sharma <chaitanya@3bandar.org>"]

[tool.poetry.dependencies]
python = "^3.7"
pytest = "^5.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
